name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: contribution-snake
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate purple snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: RenanAugustoKwn
          outputs: |
            dist/github-snake-dark.svg?color_snake=%23C084FC&color_dots=%2316102B,%233B1B66,%235B21B6,%237C3AED,%23A855F7,%23C084FC

      - name: Publish snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
          commit_message: "Update purple snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}